services:
  - type: web
    name: BloomBot_KOE
    runtime: python
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TOKEN
        value: 7750078176:AAFstaPP2l1-K3veM-RnFoSYIVq1iwK0KCA